openapi: 3.1.0
info:
  title: Editor ↔ Worker Message Contract
  version: 1.0.0
  description: >
    Web Worker 消息接口，负责 Markdown → 微信富文本转换、性能统计与兼容性提示。
servers:
  - url: webworker://conversion
paths:
  /render:
    post:
      summary: 将 Markdown 转换为微信兼容 HTML
      operationId: renderMarkdown
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenderRequest'
      responses:
        '200':
          description: 转换结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderResponse'
  /analyze:
    post:
      summary: 计算文稿统计信息与潜在兼容性问题
      operationId: analyzeMarkdown
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequest'
      responses:
        '200':
          description: 统计信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'

components:
  schemas:
    RenderRequest:
      type: object
      required:
        - markdown
        - themeId
      properties:
        markdown:
          type: string
          description: 原始 Markdown 文本
        themeId:
          type: string
          description: 主题标识
        options:
          type: object
          properties:
            enableFootnoteLinks:
              type: boolean
              default: true
            format:
              type: string
              enum: [wechat-html]
              default: wechat-html
    RenderResponse:
      type: object
      required:
        - html
        - astVersion
        - durationMs
      properties:
        html:
          type: string
          description: 兼容微信富文本的 HTML 字符串
        astVersion:
          type: integer
          description: AST 版本号，供前端缓存使用
        durationMs:
          type: number
          description: 转换耗时（毫秒）
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/CompatibilityWarning'
    AnalyzeRequest:
      type: object
      required:
        - markdown
      properties:
        markdown:
          type: string
        themeId:
          type: string
          description: 可选，指定主题用于样式验证
    AnalyzeResponse:
      type: object
      required:
        - wordCount
        - mediaStats
        - compatibilityHints
      properties:
        wordCount:
          type: integer
        mediaStats:
          type: object
          required:
            - images
            - tables
            - codeBlocks
          properties:
            images:
              type: integer
            tables:
              type: integer
            codeBlocks:
              type: integer
        compatibilityHints:
          type: array
          items:
            $ref: '#/components/schemas/CompatibilityWarning'
        recommendedActions:
          type: array
          items:
            type: string
    CompatibilityWarning:
      type: object
      required:
        - type
        - message
        - severity
      properties:
        type:
          type: string
          enum: [link, style, media, unknown]
        message:
          type: string
        severity:
          type: string
          enum: [info, warning, critical]
